# Generated by Django 3.0.2 on 2020-02-02 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nypl_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('cross_street', models.CharField(max_length=1000)),
                ('street_address', models.CharField(max_length=1000)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nypl_map.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nypl_map.Library')),
            ],
        ),
    ]
