# Generated by Django 3.0.2 on 2020-02-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nypl_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='open_time',
            field=models.TimeField(null=True),
        ),
    ]
