# Generated by Django 3.0.2 on 2020-02-12 02:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nypl_map', '0004_auto_20200212_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 12, 2, 22, 59, 286891)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 2, 12, 2, 23, 7, 194165, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hour',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 12, 2, 23, 42, 98673, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hour',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 2, 12, 2, 23, 50, 100097, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 12, 2, 23, 55, 636849, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 2, 12, 2, 23, 57, 330572, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 12, 2, 23, 58, 529516, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 2, 12, 2, 23, 59, 643549, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
