# Generated by Django 3.0.2 on 2020-02-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nypl_map', '0005_auto_20200212_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='period_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='period_start',
            field=models.DateTimeField(null=True),
        ),
    ]
