# Generated by Django 3.0.2 on 2020-02-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nypl_map', '0006_auto_20200212_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='hour',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='library',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_date',
        ),
    ]
