# Generated by Django 3.0.2 on 2020-03-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nypl_map', '0008_lastrefreshed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='library',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nypl_map.Library'),
        ),
    ]
