# Generated by Django 3.0.2 on 2020-04-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nypl_map', '0009_auto_20200308_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nypl_map.Library'),
        ),
    ]
